CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    doctor_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    appointment_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    consultation_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    status ENUM('booked', 'confirmed', 'completed', 'cancelled', 'rescheduled', 'no_show') NOT NULL DEFAULT 'booked',
    notes TEXT NULL,
    cancellation_reason VARCHAR(255) NULL,
    booking_guard_key VARCHAR(191) NOT NULL UNIQUE,
    active_booking TINYINT(1) NOT NULL DEFAULT 1,
    reminder_sent_at DATETIME NULL,
    confirmation_sent_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    CONSTRAINT fk_appointments_clinic FOREIGN KEY (clinic_id) REFERENCES clinics(id),
    CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    INDEX idx_appointments_clinic_date (clinic_id, appointment_date),
    INDEX idx_appointments_doctor_date (doctor_id, appointment_date),
    INDEX idx_appointments_patient_date (patient_id, appointment_date),
    INDEX idx_appointments_status (status),
    INDEX idx_appointments_active (active_booking)
);
