CREATE TABLE IF NOT EXISTS auth_otps (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NULL,
    patient_id BIGINT UNSIGNED NULL,
    super_admin_id BIGINT UNSIGNED NULL,
    purpose ENUM('login', 'registration', 'verification') NOT NULL DEFAULT 'login',
    channel ENUM('email', 'mobile') NOT NULL,
    challenge_token CHAR(64) NOT NULL UNIQUE,
    destination VARCHAR(191) NOT NULL,
    otp_hash CHAR(64) NOT NULL,
    delivery_status ENUM('pending', 'sent', 'failed', 'verified', 'expired') NOT NULL DEFAULT 'pending',
    delivery_error TEXT NULL,
    expires_at DATETIME NOT NULL,
    verified_at DATETIME NULL,
    consumed_at DATETIME NULL,
    attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    last_sent_at DATETIME NOT NULL,
    meta_json JSON NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    CONSTRAINT fk_auth_otps_clinic FOREIGN KEY (clinic_id) REFERENCES clinics(id),
    CONSTRAINT fk_auth_otps_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_auth_otps_super_admin FOREIGN KEY (super_admin_id) REFERENCES super_admins(id),
    INDEX idx_auth_otps_destination (channel, destination, purpose),
    INDEX idx_auth_otps_patient (patient_id),
    INDEX idx_auth_otps_super_admin (super_admin_id),
    INDEX idx_auth_otps_expires_at (expires_at),
    INDEX idx_auth_otps_delivery_status (delivery_status)
);
