CREATE TABLE IF NOT EXISTS patient_records (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    clinic_id BIGINT UNSIGNED NOT NULL,
    patient_id BIGINT UNSIGNED NOT NULL,
    appointment_id BIGINT UNSIGNED NULL,
    doctor_id BIGINT UNSIGNED NULL,
    record_type ENUM('visit_note', 'prescription', 'lab_report', 'discharge_summary', 'other') NOT NULL DEFAULT 'visit_note',
    title VARCHAR(190) NOT NULL,
    visit_summary TEXT NULL,
    document_path VARCHAR(255) NULL,
    document_mime_type VARCHAR(120) NULL,
    original_filename VARCHAR(190) NULL,
    extracted_text MEDIUMTEXT NULL,
    extracted_medications JSON NULL,
    ocr_status ENUM('not_requested', 'manual', 'completed', 'failed') NOT NULL DEFAULT 'not_requested',
    ocr_provider VARCHAR(80) NULL,
    ocr_error TEXT NULL,
    recorded_at DATETIME NOT NULL,
    created_by_type ENUM('clinic', 'patient', 'system') NOT NULL DEFAULT 'clinic',
    created_by_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    CONSTRAINT fk_patient_records_clinic FOREIGN KEY (clinic_id) REFERENCES clinics(id),
    CONSTRAINT fk_patient_records_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_patient_records_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_patient_records_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    INDEX idx_patient_records_clinic_patient (clinic_id, patient_id),
    INDEX idx_patient_records_patient_date (patient_id, recorded_at),
    INDEX idx_patient_records_appointment (appointment_id),
    INDEX idx_patient_records_type (record_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
